AllCops:
  TargetRubyVersion: 2.7.0

Layout/MultilineBlockLayout:
  Exclude:
    - '/**/spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - '/**/spec/**/*'
    - 'config/routes.rb'
    - 'Guardfile'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
    Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Lint/AmbiguousBlockAssociation:
  Enabled: false
